<?php ob_start(); ?>
<style type="text/css">
    .quote {
        margin-left: 20mm;
        text-indent: 3mm;
    }
</style>
<page backbottom="20mm">
    <p class="quote">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eros  arcu, dictum eu aliquet vel, ultrices quis orci. Mauris nec quam ac  libero consequat sodales. Nam tempor semper diam sed porta. Ut  pellentesque, turpis eget ornare mollis, dolor diam euismod tellus, at  gravida tellus nisl ac turpis. Praesent in leo massa, et eleifend  mauris. Nullam sed velit massa, ut fermentum ligula. Vivamus sit amet  tortor turpis. Sed tincidunt quam id justo pretium facilisis. Nullam  quis neque non odio suscipit sagittis. Sed bibendum elementum metus nec  hendrerit. Nam placerat sodales libero ac fringilla. Nunc ac enim eget  arcu aliquet viverra. Suspendisse cursus, quam tincidunt fringilla  condimentum, nibh orci tristique lorem, a aliquet libero urna at leo.</p>
    <p class="quote">Quisque rutrum nunc sed dolor dignissim ultricies. Nunc id pulvinar  nisl. Pellentesque habitant morbi tristique senectus et netus et  malesuada fames ac turpis egestas. Sed malesuada elit sapien, et semper  metus. Vivamus facilisis sagittis leo at cursus. In et ipsum lectus.  Integer ut velit leo. Sed venenatis blandit felis a tincidunt. Vivamus  id tellus massa, id semper nulla. Donec consectetur neque in est  fringilla sed aliquet ipsum faucibus. Morbi non augue at leo fermentum  tincidunt. Etiam blandit metus eu leo consectetur aliquam. Sed pharetra  placerat posuere. Curabitur ut elit nec justo dignissim imperdiet. Nulla  non leo quis urna cursus ultrices.</p>
    <p class="quote">Maecenas ut purus ligula. Sed neque mi, interdum elementum condimentum  eu, tempor id lacus. Sed non dolor non sapien gravida posuere sit amet  quis neque. Morbi molestie dictum lorem. Suspendisse blandit auctor  pretium. Praesent volutpat lorem vel urna facilisis volutpat. Sed  volutpat mattis molestie. Suspendisse massa leo, tempor sed aliquet ut,  vulputate et sapien. Pellentesque viverra sagittis mauris, id malesuada  tortor condimentum et. Nunc luctus dui eu dui tincidunt nec placerat  elit gravida. Vivamus ut nisi quam.</p>
    <p class="quote">Cras vel magna risus. Suspendisse et nunc diam, id rutrum neque. Fusce  sit amet est sed tortor malesuada rutrum id sed neque. Nullam blandit,  lorem a porttitor consequat, tellus mauris fringilla magna, vel pharetra  justo massa sit amet urna. Suspendisse at arcu lectus, nec sollicitudin  diam. Integer vestibulum magna ut justo viverra facilisis. Nam nec  lacus eu lacus cursus pretium eu vitae tellus. Suspendisse fermentum  felis vel nunc pharetra iaculis. Integer eu scelerisque sapien. Quisque  venenatis turpis condimentum turpis suscipit egestas.</p>
    <p class="quote">Integer fringilla vestibulum aliquet. Curabitur dui est, aliquam et  semper quis, feugiat sed sapien. Cum sociis natoque penatibus et magnis  dis parturient montes, nascetur ridiculus mus. Morbi vel nisl dolor, ut  vestibulum lectus. Nunc gravida ante ac elit suscipit lobortis. Cum  sociis natoque penatibus et magnis dis parturient montes, nascetur  ridiculus mus. Sed sagittis lobortis est vitae iaculis. Duis mollis  malesuada sodales. Nunc quis orci metus, vel sagittis dui. Curabitur  feugiat varius nulla, vitae pharetra libero condimentum sed. Mauris  sagittis commodo mattis.</p>

    <p class="quote">&nbsp;</p>
    <p class="quote">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eros   arcu, dictum eu aliquet vel, ultrices quis orci. Mauris nec quam ac   libero consequat sodales. Nam tempor semper diam sed porta. Ut   pellentesque, turpis eget ornare mollis, dolor diam euismod tellus, at   gravida tellus nisl ac turpis. Praesent in leo massa, et eleifend   mauris. Nullam sed velit massa, ut fermentum ligula. Vivamus sit amet   tortor turpis. Sed tincidunt quam id justo pretium facilisis. Nullam   quis neque non odio suscipit sagittis. Sed bibendum elementum metus nec   hendrerit. Nam placerat sodales libero ac fringilla. Nunc ac enim eget   arcu aliquet viverra. Suspendisse cursus, quam tincidunt fringilla   condimentum, nibh orci tristique lorem, a aliquet libero urna at leo.</p>
    <p class="quote">Quisque rutrum nunc sed dolor dignissim ultricies. Nunc id pulvinar   nisl. Pellentesque habitant morbi tristique senectus et netus et   malesuada fames ac turpis egestas. Sed malesuada elit sapien, et semper   metus. Vivamus facilisis sagittis leo at cursus. In et ipsum lectus.   Integer ut velit leo. Sed venenatis blandit felis a tincidunt. Vivamus   id tellus massa, id semper nulla. Donec consectetur neque in est   fringilla sed aliquet ipsum faucibus. Morbi non augue at leo fermentum   tincidunt. Etiam blandit metus eu leo consectetur aliquam. Sed pharetra   placerat posuere. Curabitur ut elit nec justo dignissim imperdiet.  Nulla  non leo quis urna cursus ultrices.</p>
    <p class="quote">Maecenas ut purus ligula. Sed neque mi, interdum elementum  condimentum  eu, tempor id lacus. Sed non dolor non sapien gravida  posuere sit amet  quis neque. Morbi molestie dictum lorem. Suspendisse  blandit auctor  pretium. Praesent volutpat lorem vel urna facilisis  volutpat. Sed  volutpat mattis molestie. Suspendisse massa leo, tempor  sed aliquet ut,  vulputate et sapien. Pellentesque viverra sagittis  mauris, id malesuada  tortor condimentum et. Nunc luctus dui eu dui  tincidunt nec placerat  elit gravida. Vivamus ut nisi quam.</p>
    <p class="quote">Cras vel magna risus. Suspendisse et nunc diam, id rutrum neque.  Fusce  sit amet est sed tortor malesuada rutrum id sed neque. Nullam  blandit,  lorem a porttitor consequat, tellus mauris fringilla magna,  vel pharetra  justo massa sit amet urna. Suspendisse at arcu lectus, nec  sollicitudin  diam. Integer vestibulum magna ut justo viverra  facilisis. Nam nec  lacus eu lacus cursus pretium eu vitae tellus.  Suspendisse fermentum  felis vel nunc pharetra iaculis. Integer eu  scelerisque sapien. Quisque  venenatis turpis condimentum turpis  suscipit egestas.</p>
    <p class="quote">Integer fringilla vestibulum aliquet. Curabitur dui est, aliquam et   semper quis, feugiat sed sapien. Cum sociis natoque penatibus et magnis   dis parturient montes, nascetur ridiculus mus. Morbi vel nisl dolor, ut   vestibulum lectus. Nunc gravida ante ac elit suscipit lobortis. Cum   sociis natoque penatibus et magnis dis parturient montes, nascetur   ridiculus mus. Sed sagittis lobortis est vitae iaculis. Duis mollis   malesuada sodales. Nunc quis orci metus, vel sagittis dui. Curabitur   feugiat varius nulla, vitae pharetra libero condimentum sed. Mauris   sagittis commodo mattis.</p>
    <p class="quote">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eros   arcu, dictum eu aliquet vel, ultrices quis orci. Mauris nec quam ac   libero consequat sodales. Nam tempor semper diam sed porta. Ut   pellentesque, turpis eget ornare mollis, dolor diam euismod tellus, at   gravida tellus nisl ac turpis. Praesent in leo massa, et eleifend   mauris. Nullam sed velit massa, ut fermentum ligula. Vivamus sit amet   tortor turpis. Sed tincidunt quam id justo pretium facilisis. Nullam   quis neque non odio suscipit sagittis. Sed bibendum elementum metus nec   hendrerit. Nam placerat sodales libero ac fringilla. Nunc ac enim eget   arcu aliquet viverra. Suspendisse cursus, quam tincidunt fringilla   condimentum, nibh orci tristique lorem, a aliquet libero urna at leo.</p>
    <p class="quote">Quisque rutrum nunc sed dolor dignissim ultricies. Nunc id pulvinar   nisl. Pellentesque habitant morbi tristique senectus et netus et   malesuada fames ac turpis egestas. Sed malesuada elit sapien, et semper   metus. Vivamus facilisis sagittis leo at cursus. In et ipsum lectus.   Integer ut velit leo. Sed venenatis blandit felis a tincidunt. Vivamus   id tellus massa, id semper nulla. Donec consectetur neque in est   fringilla sed aliquet ipsum faucibus. Morbi non augue at leo fermentum   tincidunt. Etiam blandit metus eu leo consectetur aliquam. Sed pharetra   placerat posuere. Curabitur ut elit nec justo dignissim imperdiet.  Nulla  non leo quis urna cursus ultrices.</p>
    <p class="quote">Maecenas ut purus ligula. Sed neque mi, interdum elementum  condimentum  eu, tempor id lacus. Sed non dolor non sapien gravida  posuere sit amet  quis neque. Morbi molestie dictum lorem. Suspendisse  blandit auctor  pretium. Praesent volutpat lorem vel urna facilisis  volutpat. Sed  volutpat mattis molestie. Suspendisse massa leo, tempor  sed aliquet ut,  vulputate et sapien. Pellentesque viverra sagittis  mauris, id malesuada  tortor condimentum et. Nunc luctus dui eu dui  tincidunt nec placerat  elit gravida. Vivamus ut nisi quam.</p>
    <p class="quote">Cras vel magna risus. Suspendisse et nunc diam, id rutrum neque.  Fusce  sit amet est sed tortor malesuada rutrum id sed neque. Nullam  blandit,  lorem a porttitor consequat, tellus mauris fringilla magna,  vel pharetra  justo massa sit amet urna. Suspendisse at arcu lectus, nec  sollicitudin  diam. Integer vestibulum magna ut justo viverra  facilisis. Nam nec  lacus eu lacus cursus pretium eu vitae tellus.  Suspendisse fermentum  felis vel nunc pharetra iaculis. Integer eu  scelerisque sapien. Quisque  venenatis turpis condimentum turpis  suscipit egestas.</p>
    <p class="quote">Integer fringilla vestibulum aliquet. Curabitur dui est, aliquam et   semper quis, feugiat sed sapien. Cum sociis natoque penatibus et magnis   dis parturient montes, nascetur ridiculus mus. Morbi vel nisl dolor, ut   vestibulum lectus. Nunc gravida ante ac elit suscipit lobortis. Cum   sociis natoque penatibus et magnis dis parturient montes, nascetur   ridiculus mus. Sed sagittis lobortis est vitae iaculis. Duis mollis   malesuada sodales. Nunc quis orci metus, vel sagittis dui. Curabitur   feugiat varius nulla, vitae pharetra libero condimentum sed. Mauris   sagittis commodo mattis.</p>
</page>
<page>
    <div style="width: 150px; height: 40mm; border: solid 1px red; background: #FFAAAA; text-align: left; rotate:90;">
    Rotated column 3<br/>Next line
    </div>

    <div style="border: solid 1mm red;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum, nibh eu ultricies scelerisque, est lorem dignissim elit, quis tempus tortor eros non ipsum. Mauris convallis augue ac sapien. In scelerisque dignissim elit. Donec consequat semper lectus. Sed in quam. Nunc molestie hendrerit ipsum. Curabitur elit risus, rhoncus ut, mattis a, convallis eu, neque. Morbi luctus est sit amet nunc. In nisl. Donec magna libero, aliquet eu, vestibulum ut, mollis sed, felis.</div>
    <blockquote style="border: solid 1mm red;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum, nibh eu ultricies scelerisque, est lorem dignissim elit, quis tempus tortor eros non ipsum. Mauris convallis augue ac sapien. In scelerisque dignissim elit. Donec consequat semper lectus. Sed in quam. Nunc molestie hendrerit ipsum. Curabitur elit risus, rhoncus ut, mattis a, convallis eu, neque. Morbi luctus est sit amet nunc. In nisl. Donec magna libero, aliquet eu, vestibulum ut, mollis sed, felis.</blockquote>

    <img style="float: right; margin: 10px; border: 0pt none;" src="http://www.club-seasons-voyages.com/img/images-fiche-produit/DB.jpg" border="0" alt=" " title=" " width="200" height="208" />
    <p><span style="color: #638c1f; font-size: 12pt; font-weight: bold">CLUB SEASONS VOYAGES COMMENTS</span></p>
    <p>The breathtaking views of the Pyrenees makes it an ideal setting for chamois hunting. &nbsp;Chamois stalking can be laborious and difficult at times, but ultimately rewarding! This is a great opportunity to discover or rediscover mountain hunting!</p>
    <p>&nbsp;</p>
</page>
<?php
    require_once(dirname(__FILE__).'/html2pdf.class.php');

    $html2pdf = new HTML2PDF();
    $html2pdf->writeHTML(ob_get_clean());
    $html2pdf->Output();
